### ISSUE TITLE
Release v0.6

### ISSUE THREAD

**Issue by sk1p** [LiberTEM/LiberTEM-blobfinder#89]
What's missing, anything TODO before we can cut a release?

## TODO

- [x] #90
- [x] Update changelog in the docs #95
- [ ] Jülich DATA publication (how?)
- [x] Bump to 0.7.0.dev0 #95

**Comment by matbryan52** [comment]
> What's missing, anything TODO before we can cut a release?

For me I think it's good-to-go after #90 is sorted.

**Comment by sk1p** [comment]
rc1 is here: https://github.com/LiberTEM/LiberTEM-blobfinder/releases/tag/v0.6.0rc1 and here: https://test.pypi.org/project/libertem-blobfinder/

**Comment by uellue** [comment]
It seems that the sandbox parent was nuked some time ago

Maybe one can test against production Zenodo and just doesn't hit the button?

**Comment by matbryan52** [comment]
Ran some quick tests with the rc .whl both with and without LiberTEM (py3.10 / ubuntu). All good for the full chain.

I noticed that we don't have a convenience function that will run gridmatching on a frame or stack of frames, you're obliged to run the `Matcher` yourself or go via the LT / UDF route.

**Comment by sk1p** [comment]
> Maybe one can test against production Zenodo and just doesn't hit the button?

Implemented in #94 - once that is merged, I'll cut another RC

**Comment by sk1p** [comment]
rc2 is building here, let's specifically check the zenodo part: https://github.com/LiberTEM/LiberTEM-blobfinder/actions/runs/8720954308

**Comment by uellue** [comment]
RC2 looks good on Zenodo!

**Comment by sk1p** [comment]
I'll go ahead and tag v0.6.0 then!

**Comment by sk1p** [comment]
pypi upload is failing for some reason, I'll take care of it...

**Comment by sk1p** [comment]
> pypi upload is failing for some reason, I'll take care of it...

Fixed by rotating credentials: https://pypi.org/project/libertem-blobfinder/

**Comment by sk1p** [comment]
> I'll go ahead and tag v0.6.0 then!

For some reason, the zenodo part now failed, see the log here: https://github.com/LiberTEM/LiberTEM-blobfinder/actions/runs/8721100857/job/23924930249

**Comment by uellue** [comment]
Hm, maybe because I had it open, or because it is irritated by the draft from the RC? Wasn't an issue before, so IDK, try again?

**Comment by sk1p** [comment]
GitHub release notes published here: https://github.com/LiberTEM/LiberTEM-blobfinder/releases/tag/v0.6.0

Changelog in the docs still needs to be consolidated.

> Hm, maybe because I had it open, or because it is irritated by the draft from the RC? Wasn't an issue before, so IDK, try again?

Hm, can't easily re-run the job, as the zenodo upload comes after pypi, and pypi will complain loudly about the already existing release. Might need to run it carefully, manually (I don't have the credentials for that though).

**Comment by sk1p** [comment]
> What about cutting 0.6.1, [...]

Ok, I'll do that.

**Comment by sk1p** [comment]
> I dig out the notebook to run this manually, with keys etc?

Looks like that is needed. I think a good idea would be not to use the notebook, but the release script instead, so we are testing the thing that we are actually running in CI

**Comment by uellue** [comment]
https://zenodo.org/records/10986304

**Comment by sk1p** [comment]
> https://doi.org/10.5281/zenodo.10986304

Still not there btw. - should check again tomorrow and maybe file a support issue with zenodo

**Comment by sk1p** [comment]
I'll manually contact the DOI people about the 404, and consider this done.

**Comment by sk1p** [comment]
Released on conda-forge (still waiting for CDN - can be confirmed with `conda search libertem-blobfinder`) https://github.com/conda-forge/libertem-blobfinder-feedstock/pull/1
